package network;


import java.io.Serializable;
import java.util.concurrent.ConcurrentHashMap;

public class ProcessInfo implements java.io.Serializable {
	/**
	 * Autogenerated
	 */
	private static final long serialVersionUID = 1432283007962668575L;
	public int processId; //number automatically generated by Server
	public int clientId; //client currently running this process 
	//public String processName; // this field is the key of the hashmap and not an element in the value
	public Runnable controllerRunnable;
	
	//processId, clientId, controllerThread (Runnable)
	public ProcessInfo(int p, int c,  Runnable r){
		processId = p;
		clientId = c;
		controllerRunnable = r;
	}
	
}



